// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"order_app/internal/controller"
	"order_app/internal/persistence/repository"
	"order_app/internal/service"
)

// Injectors from wire.go:

func InitAppDi() *AppDi {
	userRepo := repository.NewUserRepository()
	userService := service.NewUserService(userRepo)
	userController := controller.NewUserController(userService)
	appDi := NewAppDi(userController)
	return appDi
}

// wire.go:

var AllPublicDeps = wire.NewSet(controller.UserControllerSet)

type AppDi struct {
	UserController controller.UserController
}

func NewAppDi(userController controller.UserController) *AppDi {
	return &AppDi{
		UserController: userController,
	}
}
